language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
install:
  - "pip install construct"
# command to run tests
script:
  - "python -m unittest test.beam_construct"
  - "python -m unittest test.eetf_construct"

